#!/bin/sh
# Minimal gradlew shim. The real gradle-wrapper.jar is generated by CI
# (gradle/actions/setup-gradle) before any ./gradlew invocation.
# For local builds, run `gradle wrapper` once to materialize the jar.
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
JAR="$DIR/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$JAR" ]; then
  echo "gradle-wrapper.jar not found. Run 'gradle wrapper' once or rely on CI to generate it."
  exit 1
fi
exec java -classpath "$JAR" org.gradle.wrapper.GradleWrapperMain "$@"
